# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.4
  - nightly
notifications:
  email: false
#script:
# - julia --color=yes -e "using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end;"
# - julia --inline=no --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true);"
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  allow_failures:
  - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
env:
  global:
    - COVERALLS_PARALLEL=true
  notifications:
    webhooks: "https://coveralls.io/webhook"

